// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://avdfdxeywszdzrsifivq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF2ZGZkeGV5d3N6ZHpyc2lmaXZxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5ODcxNzYsImV4cCI6MjA3MzU2MzE3Nn0.dTCQGCsNpIrlD0yEzd6_X5C5kwUhcR_EOEdpfnH4QB4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});